Description: Typesense VPC

Parameters:
    VpcCIDR:
        Description: VPC IP range (CIDR notation)
        Type: String
        Default: 10.16.0.0/16
    PublicSubnet1CIDR:
        Description: IP range for the Public Subnet in AZ1
        Type: String
        Default: 10.16.10.0/24
    PublicSubnet2CIDR:
        Description: IP range for the Public Subnet in AZ2
        Type: String
        Default: 10.16.11.0/24
    PublicSubnet3CIDR:
        Description: IP range for the Public Subnet in AZ3
        Type: String
        Default: 10.16.12.0/24

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            - Label:
                  default: "Network Configuration"
              Parameters:
                  - VpcCIDR
                  - PublicSubnet1CIDR
                  - PublicSubnet2CIDR
                  - PublicSubnet3CIDR

Resources:
    # VPC
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: !Ref VpcCIDR
            EnableDnsSupport: true
            EnableDnsHostnames: true
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName}

    # IG
    InternetGateway:
        Type: AWS::EC2::InternetGateway
        Properties:
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName}

    # Attach IG to VPC
    InternetGatewayAttachment:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
            InternetGatewayId: !Ref InternetGateway
            VpcId: !Ref VPC

    # Public Subnet #1
    PublicSubnet1:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [0, !GetAZs ""]
            CidrBlock: !Ref PublicSubnet1CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName} Public Subnet (AZ1)

    # Public Subnet #2
    PublicSubnet2:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [1, !GetAZs ""]
            CidrBlock: !Ref PublicSubnet2CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName} Public Subnet (AZ2)

    # Public Subnet #3
    PublicSubnet3:
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref VPC
            AvailabilityZone: !Select [2, !GetAZs ""]
            CidrBlock: !Ref PublicSubnet3CIDR
            MapPublicIpOnLaunch: true
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName} Public Subnet (AZ3)

    # Public Route Table
    PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
            VpcId: !Ref VPC
            Tags:
                - Key: Name
                  Value: !Sub ${AWS::StackName} Public Routes

    # Default Route to IG
    DefaultPublicRoute:
        Type: AWS::EC2::Route
        DependsOn: InternetGatewayAttachment
        Properties:
            RouteTableId: !Ref PublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref InternetGateway

    # Public SN1
    PublicSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref PublicSubnet1

    # Public SN2
    PublicSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref PublicSubnet2

    # Public SN3
    PublicSubnet3RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref PublicRouteTable
            SubnetId: !Ref PublicSubnet3

Outputs:
    VPC:
        Description: The ID of the VPC
        Value: !Ref VPC
        Export:
            Name: !Sub ${AWS::StackName}-VPCID
    VPCCidrBlock:
        Description: The VPCCidrBlock of the VPC
        Value: !GetAtt VPC.CidrBlock
        Export:
            Name: !Sub ${AWS::StackName}-VPCCidrBlock
    PublicSubnet1:
        Description: Public Subnet 1
        Value: !Ref PublicSubnet1
        Export:
            Name: !Sub ${AWS::StackName}-PublicSubnet1
    PublicSubnet2:
        Description: Public Subnet 2
        Value: !Ref PublicSubnet2
        Export:
            Name: !Sub ${AWS::StackName}-PublicSubnet2
    PublicSubnet3:
        Description: Public Subnet 3
        Value: !Ref PublicSubnet3
        Export:
            Name: !Sub ${AWS::StackName}-PublicSubnet3
